spring.application.name=NoirTable RMS
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/noir_table
spring.jackson.time-zone=Asia/Kolkata
spring.mvc.static-path-pattern=/**

app.upload.dir=uploads
app.security.jwt.secret=restaurant-management-system-jwt-secret-key-please-change-2026
app.security.jwt.expiration-minutes=720
